# Generated by Django 3.1 on 2021-11-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('room_type', models.SmallIntegerField(choices=[(0, 'work'), (1, 'meeting')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workcalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('work_time', models.TimeField()),
                ('descript', models.TextField()),
                ('pic', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('member', models.TextField()),
                ('assign', models.CharField(max_length=50)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workcalendar.room')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('descript', models.TextField()),
                ('team_leader', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('member', models.TextField()),
                ('num_mem', models.SmallIntegerField()),
                ('loc_start', models.CharField(max_length=50)),
                ('loc_end', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=10)),
                ('ve_type', models.SmallIntegerField(choices=[(0, 'zace'), (1, 'taxi')], null=True)),
                ('plan', models.SmallIntegerField(choices=[(0, 'Ke hoach'), (1, 'Dot Xuat')], null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workcalendar.room')),
            ],
        ),
    ]
