# Generated by Django 3.2.8 on 2021-11-27 03:29

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0002_room_vehicle_workcalendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcalendar',
            name='work_date',
        ),
        migrations.RemoveField(
            model_name='workcalendar',
            name='work_time',
        ),
        migrations.AddField(
            model_name='workcalendar',
            name='worktime_from',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workcalendar',
            name='worktime_to',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
