# Generated by Django 3.2.8 on 2021-11-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0003_auto_20211127_0329'),
        ('workcalendar', '0003_auto_20211127_0432'),
    ]

    operations = [
    ]
