# Generated by Django 3.1 on 2021-12-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0004_merge_0003_auto_20211127_0329_0003_auto_20211127_0432'),
        ('workcalendar', '0004_merge_20211127_0754'),
    ]

    operations = [
    ]
