# Generated by Django 3.2.8 on 2021-12-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0005_merge_20211201_1029'),
        ('workcalendar', '0006_workcalendar_cal_check'),
    ]

    operations = [
    ]
