# Generated by Django 3.1 on 2021-12-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0008_auto_20211215_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'permissions': [('can_approve_car', 'Can approve list car')]},
        ),
        migrations.AddField(
            model_name='myuser',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workcalendar.room'),
        ),
    ]
