# Generated by Django 3.2.9 on 2021-12-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0008_auto_20211215_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workcalendar',
            options={'permissions': [('can_approve_calendar', 'can_approve_calendar'), ('can_stop_calendar', 'can_stop_calendar')]},
        ),
    ]
