# Generated by Django 3.1 on 2022-01-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0009_auto_20211222_1301'),
        ('workcalendar', '0008_auto_20211215_1323'),
    ]

    operations = [
    ]
