# Generated by Django 3.2.9 on 2021-12-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0009_alter_workcalendar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workcalendar.room'),
        ),
    ]
