# Generated by Django 3.2.9 on 2021-12-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0010_myuser_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcalendar',
            name='department',
            field=models.SmallIntegerField(null=True),
        ),
    ]
