# Generated by Django 3.1 on 2022-01-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0010_merge_20220112_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Fname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
